### ISSUE TITLE
[Request]Wikiに使用サービス一覧と料金を調べる？

### ISSUE THREAD

**Issue by nasu-oldhand** [kyuki-rp/portfolios-app#4]
## 要望の内容

Wikiに最小限の構成で2000円~3000円という制約があるため、
AWSの料金と一覧を調べる必要がありそう…

### 関連するwiki

![image](https://user-images.githubusercontent.com/81901297/127765226-20bc8165-b7e7-4221-aa6b-901d43459015.png)

**Comment by kyuki-rp** [comment]
#4
>Wikiに最小限の構成で2000円~3000円という制約があるためAWSの料金と一覧を調べる必要がありそう…
可能なら達成したい要件だから調べなくて良い！
ECSで最小構成で組むのほうが必須要件ということで！
優先順位つけてなくてごめん。

**Comment by kyuki-rp** [comment]
料金のボトルネックはECSだと思ってる。
そしてECS自体は無料で、EC2の方に料金がかかるという認識。
https://www.skyarch.net/blog/?p=14595

あってる？

**Comment by nasu-oldhand** [comment]
あってるあってる！

**Comment by nasu-oldhand** [comment]
Wiki一覧把握できるようにした

https://github.com/kyuki-rp/portfolios-app/wiki/Services

**Comment by nasu-oldhand** [comment]
じゃあとりあえずいいか

Closeしまーす

**Comment by kyuki-rp** [comment]
あざす！！
